import { generateKeyPair, randomBytes, sign, X509Certificate, type KeyObject } from "node:crypto";
import { promisify } from "node:util";

/**
 * The key pair a user's Enable Banking application signs with, and the
 * self-signed certificate Enable Banking wants for it (step 5 of their form:
 * "Public certificate in PEM format").
 *
 * The key is generated by Node (OpenSSL underneath), never leaves the worker
 * unencrypted, and is never shown to anyone. Only the certificate — public by
 * nature — goes to the user.
 *
 * Node can parse X.509 but not write it, so the certificate is assembled here
 * from DER by hand. It is one fixed, small structure (an RSA end-entity v3
 * certificate with two extensions); the tests parse every generated
 * certificate back with Node's own X509Certificate and verify its signature,
 * which keeps this honest without a certificate library in the dependency tree.
 */

const generateKeyPairAsync = promisify(generateKeyPair);

export const CERTIFICATE_VALIDITY_DAYS = 365;

export interface GeneratedCredential {
  /** PKCS#8 PEM — encrypt immediately, never log or return. */
  privateKeyPem: string;
  certificatePem: string;
  /** SHA-256 over the DER certificate, "AB:CD:…" — what the user compares. */
  fingerprint: string;
  notAfter: Date;
}

export async function generateCredential(now = new Date()): Promise<GeneratedCredential> {
  // 4096 bits, as Enable Banking's own instructions (`openssl genrsa 4096`).
  const { privateKey, publicKey } = await generateKeyPairAsync("rsa", {
    modulusLength: 4096,
    publicExponent: 0x10001,
  });
  const notBefore = new Date(now.getTime() - 5 * 60_000); // tolerate clock skew
  const notAfter = new Date(now.getTime() + CERTIFICATE_VALIDITY_DAYS * 86_400_000);
  const der = selfSignedCertificate({ privateKey, publicKey, notBefore, notAfter });
  const certificatePem = toPem(der, "CERTIFICATE");
  const parsed = new X509Certificate(certificatePem);
  // Belt and braces: never hand out a certificate that doesn't verify against
  // the key we are about to store.
  if (!parsed.verify(publicKey) || !parsed.checkPrivateKey(privateKey)) {
    throw new Error("Generated certificate does not match its key");
  }
  return {
    privateKeyPem: privateKey.export({ type: "pkcs8", format: "pem" }).toString(),
    certificatePem,
    fingerprint: parsed.fingerprint256,
    notAfter,
  };
}

// ─── DER ─────────────────────────────────────────────────────────────────

function tlv(tag: number, content: Buffer): Buffer {
  const len = content.length;
  let header: Buffer;
  if (len < 0x80) {
    header = Buffer.from([tag, len]);
  } else {
    const bytes: number[] = [];
    for (let n = len; n > 0; n >>= 8) bytes.unshift(n & 0xff);
    header = Buffer.from([tag, 0x80 | bytes.length, ...bytes]);
  }
  return Buffer.concat([header, content]);
}

const seq = (...items: Buffer[]) => tlv(0x30, Buffer.concat(items));
const set = (...items: Buffer[]) => tlv(0x31, Buffer.concat(items));
const nul = () => Buffer.from([0x05, 0x00]);
const utf8 = (s: string) => tlv(0x0c, Buffer.from(s, "utf8"));
const octets = (b: Buffer) => tlv(0x04, b);
const bitString = (b: Buffer) => tlv(0x03, Buffer.concat([Buffer.from([0x00]), b]));
const explicit = (n: number, inner: Buffer) => tlv(0xa0 | n, inner);
const bool = (v: boolean) => Buffer.from([0x01, 0x01, v ? 0xff : 0x00]);

/** Unsigned big-endian integer, minimal and positive. */
function integer(bytes: Buffer): Buffer {
  let i = 0;
  while (i < bytes.length - 1 && bytes[i] === 0) i++;
  let body = bytes.subarray(i);
  if (body[0] & 0x80) body = Buffer.concat([Buffer.from([0x00]), body]);
  return tlv(0x02, body);
}

function oid(dotted: string): Buffer {
  const parts = dotted.split(".").map(Number);
  const out: number[] = [parts[0] * 40 + parts[1]];
  for (const part of parts.slice(2)) {
    const chunk: number[] = [];
    let n = part;
    do {
      chunk.unshift(n & 0x7f);
      n = Math.floor(n / 128);
    } while (n > 0);
    for (let i = 0; i < chunk.length - 1; i++) chunk[i] |= 0x80;
    out.push(...chunk);
  }
  return tlv(0x06, Buffer.from(out));
}

/** RFC 5280: UTCTime through 2049, GeneralizedTime from 2050. */
function time(d: Date): Buffer {
  const iso = d.toISOString(); // YYYY-MM-DDTHH:MM:SS.sssZ
  const digits = iso.slice(0, 19).replace(/[-:T]/g, ""); // YYYYMMDDHHMMSS
  return d.getUTCFullYear() < 2050
    ? tlv(0x17, Buffer.from(`${digits.slice(2)}Z`, "ascii"))
    : tlv(0x18, Buffer.from(`${digits}Z`, "ascii"));
}

const OID = {
  sha256WithRSA: "1.2.840.113549.1.1.11",
  commonName: "2.5.4.3",
  organization: "2.5.4.10",
  basicConstraints: "2.5.29.19",
  keyUsage: "2.5.29.15",
};

function name(): Buffer {
  // Deliberately generic: no e-mail address or user id in a document that
  // gets copied into a third party's control panel.
  return seq(
    set(seq(oid(OID.organization), utf8("FinTrack"))),
    set(seq(oid(OID.commonName), utf8("FinTrack bank sync"))),
  );
}

function selfSignedCertificate(opts: {
  privateKey: KeyObject;
  publicKey: KeyObject;
  notBefore: Date;
  notAfter: Date;
}): Buffer {
  const algorithm = seq(oid(OID.sha256WithRSA), nul());
  const spki = opts.publicKey.export({ type: "spki", format: "der" });
  // 128 random bits, top bit cleared so the INTEGER stays positive.
  const serialBytes = randomBytes(16);
  serialBytes[0] &= 0x7f;
  serialBytes[0] |= 0x01;

  const extensions = explicit(
    3,
    seq(
      // Not a CA.
      seq(oid(OID.basicConstraints), bool(true), octets(seq())),
      // digitalSignature only.
      seq(oid(OID.keyUsage), bool(true), octets(tlv(0x03, Buffer.from([0x07, 0x80])))),
    ),
  );

  const tbs = seq(
    explicit(0, integer(Buffer.from([0x02]))), // v3
    integer(serialBytes),
    algorithm,
    name(),
    seq(time(opts.notBefore), time(opts.notAfter)),
    name(),
    spki,
    extensions,
  );
  const signature = sign("sha256", tbs, opts.privateKey);
  return seq(tbs, algorithm, bitString(signature));
}

function toPem(der: Buffer, label: string): string {
  const b64 = der.toString("base64").match(/.{1,64}/g)!.join("\n");
  return `-----BEGIN ${label}-----\n${b64}\n-----END ${label}-----\n`;
}
